name: Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'Cargo.*'
      - build.rs
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'Cargo.*'
      - build.rs

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
